### ISSUE TITLE
[Feature]  Added missing Navbar 

### ISSUE THREAD

**Issue by biswajit-sarkar-007** [PratikMane0112/TelMedSphere#10]
### Description

in your website i have noticed that the Navbar that's exist is not good enough , there is missing of footer items i will be implement this according to your project decoration 

### Screenshots

![WhatsApp Image 2024-12-13 at 11 49 06_8c8b151a](https://github.com/user-attachments/assets/d747956b-e338-4f1a-b8cc-51ef271e8f4e)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/PratikMane0112/TelMedSphere/blob/master/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a SWOC'25 contributor.
- [X] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/PratikMane0112/TelMedSphere/blob/master/.github/CODE_OF_CONDUCT.md)".

**Comment by PratikMane0112** [comment]
Hey @biswajit-sarkar-007  Welcome to 💖TelMedSphere !!!!!!! Thank you for your interest but you just get this issue in wrong way. After login only the footer items are visible in navbar. You can check it, try login with test accounts :
For patient -
username - patient@gmail.com
password - patient@gmail.com
For doctor -
username - doctor@gmail.com
password - doctor@gmail.com

**Comment by PratikMane0112** [comment]
Hey @biswajit-sarkar-007 Welcome to 💖TelMedSphere !!!!!!! Thank you for your interest but you just get this issue in wrong way. After login only the footer items are visible in navbar. You can check it, try login with test accounts :
For patient -
username - [patient@gmail.com](mailto:patient@gmail.com)
password - [patient@gmail.com](mailto:patient@gmail.com)
For doctor -
username - [doctor@gmail.com](mailto:doctor@gmail.com)
password - [doctor@gmail.com](mailto:doctor@gmail.com)
