### ISSUE TITLE
Improve FAQ Interaction with Scroll-triggered Opening

### ISSUE THREAD

**Issue by neeru24** [PratikMane0112/TelMedSphere#25]
### Current Behavior:
Users need to manually click on each FAQ question to open and view the corresponding answer. While functional, this interaction can feel cumbersome, especially on devices where scrolling is the primary mode of navigation.

### Proposed Improvement:
Modify the FAQ section so that when a user scrolls to a specific question, the answer automatically expands. This scroll-triggered behavior will enhance the user experience by reducing manual interactions and providing dynamic feedback as the user navigates through the page.

### Screenshots

![image](https://github.com/user-attachments/assets/6c4720ff-59b1-4c69-8529-63b9b9f9de72)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/PratikMane0112/TelMedSphere/blob/master/.github/CONTRIBUTING_GUIDELINES.md) of this project.
- [X] I am a SWOC'25 contributor.
- [X] I am a KWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/PratikMane0112/TelMedSphere/blob/master/.github/CODE_OF_CONDUCT.md)".

**Comment by PratikMane0112** [comment]
Hey @neeru24, WelCome to 💖TelMedSphere !!!!!! . Please go ahead. Also for any query & update join discord server (Link in discription itself)

**Comment by PratikMane0112** [comment]
Also to explore the website more, you can give a try with test accounts -
For patient -
username - [patient@gmail.com](mailto:patient@gmail.com)
password - [patient@gmail.com](mailto:patient@gmail.com)
For doctor -
username - [doctor@gmail.com](mailto:doctor@gmail.com)
password - [doctor@gmail.com](mailto:doctor@gmail.com)

Note : Do not forget to log out, when you are done
